################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean compile package install

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    tags: true

###################
### Environment ###
###################
env:
  global:
  - secure: sey+D+db/5Ga+sOQH3sDeem/j2Mt/g0zR3kwxjIQF5eLZ9HOX1nqYieIJBgaaFuA3PeXtgT7VUvBlW4A/ga308ddjhMAks89ssxdbDdXRh4u5yq3xBwHeA3K9et7APEPStYwqn1kU8sMhmVFh8GkOSWRA7Q+rg/wd67q65hZ6PCa0jwgafamU7lO1IKOTkIstDhFnF5FFSAiI9DA7687e9UbwAAgUJRt5C3BpWFn/qBa9QP50AmQ39y4QGHC8L/Fycj4DMX2RlDqTcrsK0qgHerEzsDZzli8oNUl/1MFB3IVf0tbbbkmCYK45R11YSUvLxGWBBMZd8w7Nyd50aevLay5O4dJhto1FMKPPVUgYvhc9m3MRskYb1QyiPzyKc8SxAUJHR4ustDS/iZ2sZkaPJXe0GbF8MmDgwXcPPAMJiTiN3Dh6CP8Fl123V53JcZc+uWtS3bxArUa5LGZJFIBWh2jXL2pf6nDUPJrofMUSpgC5/EBQSlbo4YwqOZVMttxqhWmQKIn8KHI/5UEXsSyTHB5xaddn6n9i8zbAvmXOoEK48meiY8/gxcNss9cu0C4yg1qnlGvPN9/aInz6x3SG4vwU/RR4uI3CxBj/LHdmEiyhHn99ZWyDhxSd4mcngfDXWQChYjA7/dsG0GNHxnFyzjXSyl2F/mCDvfdyhEnJdQ=
  - secure: kzPDISOWTt88J2OjxJZQEkDvBzQcfFMQ3Hi7O2t0ER1JIXlHYp6+U/Kzb4W0W5HVz66Vpq2OyO6btAwaA4RCoyo6JPwLTc3fSLNAOP2R3lLe+ycxVulgKpPZ96Po6ax4he5dTYsxrGa/teGgRzOfNA8MHM9Sfz+lkiKT0bX9O1KUwMnP7kmuu2TKZ/PDaOAluOe/hQ5OADfGAc+k2/3h7FcSwyDH5+6VJQz8+B80jzMgu2hwwfSSMwXCEyhmm2QggSD/DTC1Ci9CFtHusJrWbCu5P1J9+Y/MSzJmoPdWPfDCcLz9abWQN9Y9/mR4/pbu/IVOweeVAYOSatntQ4V+Wn30FQ1+8e97w6RP2cpz2hw0fNQvSKj8cOwOzvef9fLMCOWEaIqcbx1TU44xK1E+YjIFFZGki8K0PzOEezsiDMZlSw3QNHz0PSA1fLocmsu+KuC3pmKmBooUkI+6OAkBTDTPYz0P7SsfvzElpuociFZFIlpFmiUnzSRRO1p3e4XNQGWg1sA9qcVk4a5IemcLmDkm6tkQtqPT3GP+ZdBMfVT+TWWQNKh+EdhdqB9jzuo8HajlCSuOAPNPjc4VsVA1VssQbxfIMVlG0cp6ekER/mevw1hCRAxzN40oOqmZVzDfgREqBTogE+8pussxTG17PqGKmZIYJUvG4KqCHq5x6Bg=
